# Core
source = hypr/monitors.conf
source = hypr/programs.conf
source = hypr/autostart.conf
source = hypr/env.conf
source = hypr/design.conf
source = hypr/animations.conf
source = hypr/input.conf
source = hypr/layout.conf
source = hypr/binds.conf
source = hypr/rules.conf
# Plugin configuration for virtual-desktops
##plugin {
#    virtual-desktops {
#        names = 1:coding, 2:internet, 3:mail and chats
#        cycleworkspaces = 1
#        rememberlayout = size
#        notifyinit = 0
#        verbose_logging = 0
#    }
#}
