# Suppress maximize requests
windowrule = suppress_event maximize, match:class .*

# Fix XWayland focus
windowrule = no_focus true, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Dedicated workspaces
#windowrule = workspace 1, match:class ^(kitty)$
#windowrule = workspace 2, match:class ^(firefox)$
#windowrule = workspace 3, match:class ^(firefox-priv)$

layerrule = blur true, match:namespace waybar # Add blur to waybar
layerrule = blur_popups true, match:namespace waybar # Blur waybar popups too!
layerrule = ignore_alpha 0.2, match:namespace waybar # Make it so transparent parts are ignored
# (Optional) Smart-gaps / per-workspace tweaks
# workspace = w[tv1], gapsout:0, gapsin:0
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
