# Core
source = monitors.conf
source = programs.conf
source = autostart.conf
source = env.conf
source = design.conf
source = animations.conf
source = input.conf
source = layout.conf
source = binds.conf
source = rules.conf
# Plugin configuration for virtual-desktops
##plugin {
#    virtual-desktops {
#        names = 1:coding, 2:internet, 3:mail and chats
#        cycleworkspaces = 1
#        rememberlayout = size
#        notifyinit = 0
#        verbose_logging = 0
#    }
#}
